import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend QR Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>


        <div className={styles.card}>
          <div className={styles.cardContent}>
            <Image
              className={styles.logo}
              src="/image-qr-code.png"
              alt="QR Code frontend.io"
              width={260}
              height={260}
            />
          
            <h2 className={styles.h2}>
              Improve your front-end skills by building projects
            </h2>

            <div className={styles.description}>
              <p>
                Scan the QR code to visit Frontend Mentor and take your coding skills to the next level
              </p>
            </div>
          </div>
        </div>


      </main>
    </>
  )
}
